# Generated by Django 3.1.12 on 2025-01-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_utils', '0001_initial'),
        ('course_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutline',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization_utils.organization'),
        ),
    ]
