services:
  # Frontend build (separate from Nginx)
  frontend:
    build:
      context: ./consumer_frontend/
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/app/dist

  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot:certbot
    environment:
      - EMAIL=${CERTBOT_EMAIL}
      - DOMAIN=${ALLOWED_HOSTS}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'certbot certonly --webroot -w /var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}'"
    command: "/bin/sh -c 'while :; do certbot renew; sleep 12h; done'"

  # Backend service
  backend:
    image: consumer-backend:latest
    ports:
      - "8000:8000" # Maps port 8000 of the host to port 8000 of the container
    networks:
      - app-network
    env_file: .env
    environment:
      DB_HOST: mongo
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: mysite.settings
    depends_on:
      - mongo
      - redis

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

# Define a common network for all services
networks:
  app-network:
    driver: bridge

# Define volumes for persistent storage
volumes:
  mongo_data:
  redis_data:
  frontend_build:
