services:
  # Frontend service
  frontend:
    image: consumer-frontend:latest # Replace with your frontend Docker image
    ports:
      - "3000:3000" # Maps port 3000 of the host to port 3000 of the container
    env_file: .env
    networks:
      - app-network
    depends_on:
      - backend

  # Backend service
  backend:
    image: consumer-backend:latest # Replace with your backend Docker image
    ports:
      - "8000:8000" # Maps port 7001 of the host to port 7001 of the container
    networks:
      - app-network
    env_file: .env
    environment:
      DB_HOST: mongo # Referencing the Mongo service by its container name
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: mysite.settings
    depends_on:
      - mongo
      - redis

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017" # Maps port 27017 of the host to port 27017 of the container
    volumes:
      - mongo_data:/data/db # Persistent storage for MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379" # Maps port 6379 of the host to port 6379 of the container
    volumes:
      - redis_data:/data # Persistent storage for Redis
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Maps port 80 of the host to port 80 of the container
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Replace with your nginx configuration
    depends_on:
      - frontend
      - backend

# Define a common network for all services
networks:
  app-network:
    driver: bridge

# Define volumes for persistent storage
volumes:
  mongo_data:
  redis_data: