# Generated by Django 3.1.12 on 2025-01-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('EM', 'Employee'), ('AD', 'Admin'), ('OW', 'Owner')], default='EM', max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_utils.organization')),
            ],
        ),
    ]
