# Generated by Django 3.1.12 on 2025-01-19 00:11

from django.db import migrations, models
import organization_utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('verification_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='user_name',
            field=organization_utils.models.FullNameField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(default=organization_utils.models.generate_user_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('EM', 'Employee'), ('AD', 'Admin'), ('OW', 'Owner'), ('SU', 'Suspended')], default='EM', max_length=2),
        ),
    ]
