# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory
WORKDIR /app/

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install dependencies for development
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose port 3000
EXPOSE 3000

# Command to run the development server
CMD ["npm", "run", "dev"] 